baseURL = 'https://lovely-sable-11cf24.netlify.app/'
title   = "Rest Science"
languageCode = "en-us"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

disableKinds = ["taxonomy"]

[permalinks]
  posts = "/posts/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.6
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  minifyOutput = false

[params]
  site_description = "Clear, practical sleep gear guides."
  author = "Rest Science"
  showReadingTime = true
